Update hadoopsetup

diff --git a/hadoopsetup b/hadoopsetup
--- a/hadoopsetup
+++ b/hadoopsetup
@@ -90,7 +90,7 @@ mv ${HADOOPVER} hadoop
 chown -R ${HADOOPUSER}:${HADOOPGRP} hadoop
 echo "[INFO]  Copied hadoop" 1>&2
 else
-echo "[INFO]  Hadoop folder already exists - delete /usr/local/hadoop to re-install" 1>&2
+echo "[INFO]  Hadoop folder already exists - delete /usr/local/hadoop to re-install!" 1>&2
 fi
 
 # copy java  if not setup already.
@@ -107,12 +107,12 @@ if [ $? -eq 1 ]; then
     echo >&2 "[INFO]  Java not found."
 else
    JAVA_VER=$(java -version 2>&1 | sed 's#java version "\(.*\)\(.*\)\.*"#\1\2#; 1q')
-   echo "[INFO]  Installed java is ${JAVA_VER}"
+   echo "[INFO]  Currently installed java is ${JAVA_VER}"
 fi
 
-echo "[INFO]  Required java is ${JAVA_REQ_VER}"
+echo "[INFO]  Required java is ${JAVAREQVER}"
 if [ ${JAVA_VER} != ${JAVAREQVER} ]; then
-  echo "[INFO]  Updateing java to ${JAVA_REQ_VER}"
+  echo "[INFO]  Updateing java to ${JAVAREQVER}"
   sleep 5s
   cp -r  /mnt/share/hadoop/java/64/jdk${JAVAREQVER}/ /usr/local/java/
   cd /usr/local/java
